apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bpdmsawardperiod
  name: bpdmsawardperiod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bpdmsawardperiod
  template:
    metadata:
      labels:
        app: bpdmsawardperiod
    spec:
      containers:
        - name: bpdmsawardperiod
          image: cstardacr.azurecr.io/bpdmsawardperiod
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: postgres-credentials
            - secretRef:
                name: application-insights
            - configMapRef:
                name: eventhub-logging
            - configMapRef:
                name: bpdmsawardperiod
            - configMapRef:
                name: jvm
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 20
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 30
      hostAliases:
        - hostnames:
            - bpd-hub-dev.servicebus.windows.net
          ip: 10.70.5.9
