apiVersion: apps/v1
kind: Deployment
metadata:
  name: bpdmsawardperiod 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bpdmsawardperiod
  template:
    metadata:
      labels:
        app: bpdmsawardperiod 
    spec:
      containers:
        - name: bpdmsawardperiod 
          image: cstarregistry.azurecr.io/bpdmsawardperiod
          ports:
          - containerPort: 8080